import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :orbitorc_web, OrbitorcWeb.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# No forced SSL. The control plane is a LAN service that agents dial into over `ws://` and a dashboard is
# opened at over `http://`; `force_ssl` answered both with a 301 to an https port nothing listens on, and
# Plug.SSL exempts only localhost, so the box beside the control plane joined and every other refused.
# TLS, where it is wanted, is a proxy's job in front of this process.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
